### ISSUE TITLE
Russian (Русский) <ru.cfg>

### ISSUE THREAD

**Issue by zer0Kerbal** [zer0Kerbal/SpaceYLifters#58]
# Localization - ![Русский][RU] Russian (Русский) <ru.cfg>

## GitHub

* [x] assign
  * [x] zer0Kerbal
  * [x] Repo Localization Project
  * [x] Label: type: localization
  * [x] Label: help-wanted
  * [x] Milestone: Localization - Master

### GameData

* [x] add  Localization\[ru.cfg] 🗃️

### Translation

* [x] ![Русский][RU] Russian (Русский) <ru.cfg>

### Documentation

* [x] Update [readme.md] 🔢
* [x] Update [release.md] 🧾

### Wiki

* [x] Update docs/[localization.md]

## Update Social Media

* [x] GitHub (automated) (zer0Kerbal/zer0Kerbal)
* [x] CurseForge
* [x] Reddit
* [x] Twitter @zer0Kerbal
* [x] Forum
* [x] Patreon
* [x] SpaceDock
* [x] CKAN (automated)

[lclztn]: https://github.com/zer0Kerbal/zer0Kerbal/blob/master/Localization/readme.md  "Localization"
[qs]: https://github.com/zer0Kerbal/zer0Kerbal/blob/master/Localization/quickstart.md "Quick Start"

[RU]: https://raw.githubusercontent.com/zer0Kerbal/zer0Kerbal/master/img/RU.png "Русский"

this file: © All Rights Reserved by zer0Kerbal

**Comment by evanisrael** [comment]
@zer0Kerbal done:)
PR link:
https://github.com/zer0Kerbal/SpaceYLifters/pull/116
